# Generated by Django 3.0.6 on 2020-05-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chainchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='chainchain.Level'),
        ),
    ]
