# Generated by Django 3.0.6 on 2020-05-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chainchain', '0002_auto_20200521_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='chainchain.Level'),
        ),
    ]
